### ISSUE TITLE
Dependencies issue in package.json

### ISSUE THREAD

**Issue by warmcreators-us** [warmcreators-us/Warmcreators.us#1]
### Describe the feature you'd like to request

In the main directory there is a Dependencies issue while reading the file.

### Describe the solution you'd like

Take a look at package.json and do the needful changes so that the project will not have the issues while using the Dependencies.

### Describe alternatives you've considered

Either make change in the file or create a new file to do so.

**Comment by Tarunsharmadoc** [comment]
Please assign this issue to me i might have a solution.

**Comment by warmcreators-us** [comment]
> Please assign this issue to me i might have a solution.

Ok Go ahead.
